"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AnimateIn from "@/components/AnimateIn";
import Button from "@/components/Button";
import { trackEvent } from "@/lib/analytics";
import { cn } from "@/lib/utils";
import { Eye, Trash2, Shield } from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "https://mythcipher-automation-backend.onrender.com";

const CATEGORIES = ["Social Media", "Email", "Content & Growth"];

const STATIC_USE_CASES: Record<string, Array<{ title: string; description: string; image: string; isTrending?: boolean; isComingSoon?: boolean }>> = {
  "Social Media": [
    { title: "LinkedIn Automation", description: "AI writes your LinkedIn posts, schedules them at optimal times, and tracks engagement. Grow your professional brand on autopilot.", image: "/images/feature1.png", isTrending: true },
    { title: "YouTube Scheduling", description: "Schedule uploads, auto-generate titles, descriptions, and tags. Your YouTube channel runs on autopilot.", image: "/images/feature3.png", isTrending: true },
    { title: "Instagram Automation", description: "Schedule posts, reels, and stories with AI-generated captions and hashtags. Your Instagram, automated.", image: "/images/feature5.png", isComingSoon: true },
  ],
  Email: [
    { title: "Cold Email Campaigns", description: "AI writes personalised cold emails, sends them on schedule, and follows up automatically. Never miss a potential client.", image: "/images/feature2.png", isTrending: true },
    { title: "Newsletter Automation", description: "Generate and send weekly newsletters to your subscribers with AI-written content. Build audience trust automatically.", image: "/images/feature4.png" },
    { title: "Follow-up Sequences", description: "Automated follow-up emails after meetings, proposals, or invoices. Polite, timed, and consistent \u2014 without lifting a finger.", image: "/images/feature6.png" },
  ],
  "Content & Growth": [
    { title: "AI Content Strategy", description: "Get a weekly content plan tailored to your niche. Post ideas, captions, hashtags, and optimal posting times \u2014 all generated by AI.", image: "/images/timeline.png" },
    { title: "Multi-Platform Scheduling", description: "Write once, schedule across LinkedIn, YouTube, and Instagram. AI adapts the content for each platform automatically.", image: "/images/linearinsights.png" },
    { title: "Growth Analytics", description: "Track what\u2019s working across platforms. AI recommendations on what to post more, when to post, and how to grow faster.", image: "/images/foundation.png" },
  ],
};

const GUIDED_ENTRIES = [
  { title: "Grow on LinkedIn", desc: "AI-generated posts, scheduled publishing, engagement growth.", filter: "Social Media" },
  { title: "Run email campaigns", desc: "Cold outreach, newsletters, and follow-ups on autopilot.", filter: "Email" },
  { title: "Schedule YouTube", desc: "Upload scheduling, metadata generation, and channel management.", filter: "Social Media" },
  { title: "Get a content strategy", desc: "AI plans your content calendar across all platforms.", filter: "Content & Growth" },
];

const TRUST_CARDS = [
  { icon: Eye, title: "We see configuration, not content", desc: "MythCipher stores what your automation should do and whether it ran. Never the data that flows through it." },
  { icon: Trash2, title: "Delete everything, anytime", desc: "One click in Settings removes your account, automations, and every log. Gone." },
  { icon: Shield, title: "Secure by design", desc: "Your credentials are encrypted. Your data stays yours. We never access your accounts beyond what\u2019s needed to run your automations." },
];

const INTEGRATIONS = ["LinkedIn", "YouTube", "Instagram", "Telegram", "Gmail"];

export default function UseCasesPage() {
  const [activeTab, setActiveTab] = useState("Social Media");
  const [useCases, setUseCases] = useState<Record<string, any[]>>(STATIC_USE_CASES);

  useEffect(() => {
    fetch(`${API_BASE}/api/use-cases`)
      .then((res) => res.json())
      .then((data: any[]) => {
        if (data.length > 0) {
          const grouped: Record<string, any[]> = {};
          CATEGORIES.forEach((c) => { grouped[c] = []; });
          data.forEach((uc) => {
            if (grouped[uc.category]) grouped[uc.category].push(uc);
          });
          // Only replace if we have data
          const hasData = Object.values(grouped).some((arr) => arr.length > 0);
          if (hasData) setUseCases(grouped);
        }
      })
      .catch(() => {});
  }, []);

  return (
    <div className="bg-Background font-sans overflow-x-hidden min-h-screen">
      <Header />
      <main className="pt-10">
        {/* Hero */}
        <section className="py-16 sm:py-20 px-5 md:px-8">
          <div className="max-w-5xl mx-auto space-y-8 text-center">
            <AnimateIn>
              <p className="text-sm font-medium text-Accent-Purple tracking-wide">Use Cases</p>
              <h1 className="font-serif text-3xl sm:text-4xl md:text-6xl text-Surface-Hover tracking-tight font-semibold mt-3">
                Pick what to automate. We handle the rest.
              </h1>
              <p className="text-Tertiary text-sm sm:text-base mt-4 max-w-xl mx-auto">
                LinkedIn, YouTube, email, Instagram  choose your automation and get it running in minutes. More templates going live every week.
              </p>
            </AnimateIn>
          </div>
        </section>

        {/* Guided entry */}
        <section className="py-10 sm:py-14 px-5 md:px-8 bg-Background-Alt">
          <div className="max-w-5xl mx-auto space-y-8">
            <AnimateIn>
              <h2 className="font-serif text-xl sm:text-2xl md:text-3xl text-Surface-Hover tracking-tight text-center font-semibold">
                Not sure where to start? Pick a goal.
              </h2>
            </AnimateIn>
            <div className="grid sm:grid-cols-2 gap-4">
              {GUIDED_ENTRIES.map((entry, i) => (
                <AnimateIn key={entry.title} delay={0.05 + i * 0.06}>
                  <button
                    onClick={() => {
                      setActiveTab(entry.filter);
                      trackEvent("guided_entry_click", { label: entry.title });
                      document.getElementById("use-case-grid")?.scrollIntoView({ behavior: "smooth" });
                    }}
                    className="text-left bg-Card border border-Bento-Border rounded-2xl p-5 space-y-2 hover:border-Accent-Purple/40 hover:bg-Card-Hover transition-all duration-200 cursor-pointer w-full"
                  >
                    <h3 className="text-base font-semibold text-Surface-Hover">{entry.title}</h3>
                    <p className="text-sm text-Tertiary">{entry.desc}</p>
                  </button>
                </AnimateIn>
              ))}
            </div>
          </div>
        </section>

        {/* Use-case grid */}
        <section id="use-case-grid" className="py-16 sm:py-20 md:py-28 px-5 md:px-8">
          <div className="max-w-5xl mx-auto space-y-10">
            {/* Tabs */}
            <div className="flex gap-2 overflow-x-auto scrollbar-hide">
              {CATEGORIES.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveTab(cat)}
                  className={cn(
                    "px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all duration-200 cursor-pointer",
                    activeTab === cat
                      ? "bg-Accent-Purple/10 text-Accent-Purple border border-Accent-Purple/30"
                      : "text-Tertiary hover:text-Surface border border-transparent"
                  )}
                >
                  {cat}
                </button>
              ))}
            </div>

            {/* Cards */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {(useCases[activeTab] || []).map((uc: any, i: number) => {
                const name = uc.title || uc.name;
                const desc = uc.description || uc.desc;
                const img = uc.image || "/images/feature1.png";
                const badge = uc.isComingSoon ? "Coming Soon" : uc.isTrending ? "Trending" : uc.badge;

                return (
                  <AnimateIn key={name} delay={0.05 + i * 0.08}>
                    <div className="bg-Card border border-Bento-Border rounded-2xl overflow-hidden group hover:border-Accent-Purple/30 transition-all duration-300 h-full flex flex-col">
                      <div className="relative aspect-video overflow-hidden bg-Background">
                        <Image src={img} alt={name} fill className="object-cover opacity-80 group-hover:opacity-100 group-hover:scale-105 transition-all duration-500" />
                        {badge && (
                          <div className="absolute top-3 right-3">
                            <span className={cn("text-xs px-2 py-1 rounded-full font-medium", badge === "Coming Soon" ? "bg-Accent-Yellow/20 text-Accent-Yellow" : "bg-Accent-Cyan/20 text-Accent-Cyan")}>
                              {badge}
                            </span>
                          </div>
                        )}
                      </div>
                      <div className="p-5 space-y-3 flex-1 flex flex-col">
                        <h3 className="text-base font-semibold text-Surface-Hover">{name}</h3>
                        <p className="text-sm text-Tertiary leading-relaxed flex-1">{desc}</p>
                        <div className="pt-2">
                          <Link href={`https://ai.mythcipher.in/signup?utm_source=landing&utm_medium=templates&utm_campaign=${encodeURIComponent(name)}`}>
                            <Button variant="ghost" size="small" onClick={() => trackEvent("use_case_click", { label: name })}>
                              {badge === "Coming Soon" ? "Join Waitlist \u2192" : "Try it Free \u2192"}
                            </Button>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </AnimateIn>
                );
              })}
            </div>
          </div>
        </section>

        {/* Trust */}
        <section className="py-16 sm:py-20 md:py-28 px-5 md:px-8 bg-Background-Alt">
          <div className="max-w-5xl mx-auto space-y-10">
            <AnimateIn className="space-y-3 text-center max-w-2xl mx-auto">
              <p className="text-sm font-medium text-Accent-Green tracking-wide">Your data is safe</p>
              <h2 className="font-serif text-2xl sm:text-3xl md:text-4xl text-Surface-Hover tracking-tight font-semibold">
                Your accounts. Your data. Always.
              </h2>
            </AnimateIn>

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {TRUST_CARDS.map((card, i) => (
                <AnimateIn key={card.title} delay={0.1 + i * 0.1}>
                  <div className="bg-Card border border-Bento-Border rounded-2xl p-5 sm:p-6 space-y-3 h-full">
                    <card.icon size={22} className="text-Accent-Green" />
                    <h3 className="text-base font-semibold text-Surface-Hover">{card.title}</h3>
                    <p className="text-sm text-Tertiary leading-relaxed">{card.desc}</p>
                  </div>
                </AnimateIn>
              ))}
            </div>

            <AnimateIn delay={0.4} className="text-center space-y-4">
              <p className="text-sm text-Tertiary font-medium">Platforms we integrate with</p>
              <div className="flex flex-wrap justify-center gap-2 sm:gap-3">
                {INTEGRATIONS.map((name) => (
                  <div key={name} className="px-3 sm:px-4 py-2 bg-Card border border-Bento-Border rounded-xl text-xs sm:text-sm text-Tertiary font-medium">
                    {name}
                  </div>
                ))}
              </div>
            </AnimateIn>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
